export const ADD_EMAIL = 'ADD_EMAIL';
export const REQUEST_DATA_CURRENCIES = 'REQUEST_DATA_CURRENCIES';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const FAILED_REQUEST = 'FAILED_REQUEST';
export const ADD_EXPENSES = 'ADD_EXPENSES';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const SEND_EDIT_TO_GLOBAL = 'SEND_EDIT_TO_GLOBAL';
